package app.com._paws.domain.enums;

public enum Specialty {
    CIRURGIA,
    PATOLOGIA,
    ACUPUNTURA,
    DIAGNOSTICO_POR_IMAGEM,
    ANESTESIOLOGIA,
    MEDICINA_VETERINARIA_DO_COLETIVO,
    ENDOCRINOLOGIA,
    MEDICINA_DE_ANIMAIS_SELVAGENS,
    MEDICINA_INTENSIVA_VETERINARIA,
    DERMATOLOGIA,
    CARDIOLOGIA,
    OFTALMOLOGIA,
    HOMEOPATIA,
    ONCOLOGIA,
    INSPECAO_HIGIENICA_SANITARIA_E_TECNOLOGICA,
    NEFROLOGIA_E_UROLOGIA,
    NUTRICAO_E_NUTROLOGIA
}